[[req_nwsviz-application_data-query-cube]]

[requirement]
====
[%metadata]
identifier:: /req/nwsviz-application/data-query-cube
statement:: The Vertical extent demo Collection _SHALL_ provide support for *Cube* queries 
part:: The *Cube* query _SHALL_ support the following output formats:

        * GRIB2
        * NetCDF4
        * CoverageJSON

part:: The default output format for the *Cube* query _SHALL_ be *GRIB2*

part:: The *Cube* query _SHALL_ support the following Coordinate Reference Systems:

        * GEOGCRS["WGS 84",ENSEMBLE["World Geodetic System 1984 ensemble",MEMBER["World Geodetic System 1984 (Transit)"],MEMBER["World Geodetic System 1984 (G730)"],MEMBER["World Geodetic System 1984 (G873)"],MEMBER["World Geodetic System 1984 (G1150)"],MEMBER["World Geodetic System 1984 (G1674)"],MEMBER["World Geodetic System 1984 (G1762)"],MEMBER["World Geodetic System 1984 (G2139)"],MEMBER["World Geodetic System 1984 (G2296)"],ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1]],ENSEMBLEACCURACY[2.0]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],CS[ellipsoidal,2],AXIS["geodetic latitude (Lat)",north,ORDER[1],ANGLEUNIT["degree",0.0174532925199433]],AXIS["geodetic longitude (Lon)",east,ORDER[2],ANGLEUNIT["degree",0.0174532925199433]],USAGE[SCOPE["Horizontal component of 3D system."],Area["World."],BBOX[-90,-180,90,180]],ID["EPSG",4326]]


part:: The *Cube* query _SHALL_ support the following HTTP methods:

        * GET
        * POST


====