[[req_nwsviz-application_status-codes]]

[requirement]
====
[%metadata]
identifier:: /req/nwsviz-application/status-codes
statement:: The NWSViz profile Collection profile _SHALL_ support the following HTTP status codes.
part:: The message descriptions _SHALL_ be as follows:

!===
|Status code |Description

| 200  |A successful request.

| 400  |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.

| 404  |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.

!===
====

[requirement]
====
[%metadata]
identifier:: /req/nwsviz-application/msg-bodies
statement:: The NWSViz profile Collection profile _SHALL_ support the following HTTP response body.
part:: The NWSViz profile Collection _SHALL_ use the following JSON schema for error response bodies (HTTP Status Codes 400 and above) 

[source,JSON]
----
{
    "type": "object",
    "required": [
        "code"
    ],
    "properties": {
        "code": {
            "type": "string"
        },
        "description": {
            "type": "string"
        }
    }
}
----

====