[[req_nwsviz-application_data-query-locations]]

[requirement]
====
[%metadata]
identifier:: /req/nwsviz-application/data-query-locations
statement:: All Collections in the Service _SHALL_ provide support for *Locations* queries 
part:: The *Locations* query _SHALL_ support the following output formats:

        * GeoJSON

part:: The default output format for the *Locations* query _SHALL_ be *GeoJSON*
part:: The *Locations* query _SHALL_ support the following HTTP methods:

        * GET
        * POST


part:: The *Locations* query _SHALL_ provide a listing of the available locations in a collection that conforms to GeoJSON. The GeoJSON should contain properties as shown below. Note that the example below only contains one parameter in the parameter-names-dict, but in reality it should contain all of the parameters listed in the parameter-names property.

[source,JSON]
....
{
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "geometry":{
            "type":"Polygon",
            "coordinates":[
               [
                  [
                     2681912.2261628294,
                     -263793.73346456443
                  ],
                  [
                     2681912.2261628294,
                     3789572.2545354357
                  ],
                  [
                     -3271151.605837171,
                     3789572.2545354357
                  ],
                  [
                     -3271151.605837171,
                     -263793.73346456443
                  ],
                  [
                     2681912.2261628294,
                     -263793.73346456443
                  ]
               ]
            ]
         },
         "properties":{
            "instance":"2025-09-22T00:00:00",
            "name":"conus",
            "name_alt":"http://edr-api-desi-c.mdl.nws.noaa.gov/collections/NBM_icechunk/instances/2025-09-22T00:00:00/locations/conus?f=json",
            "edrqueryendpoint":"http://edr-api-desi-c.mdl.nws.noaa.gov/collections/NBM_icechunk/instances/2025-09-22T00:00:00/locations/conus?f=json",
            "parameter-names":[
               "apparent_temperature",
               "ceiling",
               "ceiling_probability",
               "cloud_base",
               "conditional_probability_of_precipitation_type",
               "convective_available_potential_energy",
               "convective_available_potential_energy_percentiles",
               "convective_available_potential_energy_standard_deviation",
               "dewpoint",
               "dewpoint_standard_deviation",
               "downward_shortwave_radiation_flux",
               "dry_thunderstorm_probability",
               "echo_top",
               "ellrod_index",
               "fosberg_index_06_hour",
               "ice_accumulation_01_hour",
               "ice_accumulation_06_hour",
               "ice_accumulation_06_hour_percentiles",
               "low_level_turbulence",
               "low_level_wind_shear_altitude",
               "low_level_wind_shear_direction",
               "low_level_wind_shear_magnitude",
               "maximum_reflectivity",
               "maximum_relative_humidity_12_hour",
               "maximum_temperature_12_hour",
               "maximum_temperature_12_hour_standard_deviation",
               "minimum_relative_humidity_12_hour",
               "minimum_temperature_12_hour",
               "minimum_temperature_12_hour_standard_deviation",
               "mixing_height",
               "precipitable_water",
               "precipitable_water_percentiles",
               "precipitation_01_hour_probability",
               "precipitation_06_hour_probability",
               "precipitation_12_hour_probability",
               "precipitation_accumulation_01_hour",
               "precipitation_accumulation_06_hour",
               "precipitation_duration_12_hour",
               "predominant_weather",
               "relative_humidity",
               "sea_surface_temperature",
               "snow_accumulation_01_hour",
               "snow_accumulation_01_hour_percentiles",
               "snow_accumulation_06_hour",
               "snow_accumulation_06_hour_percentiles",
               "snow_level",
               "snow_level_percentiles",
               "snow_liquid_ratio",
               "snow_liquid_ratio_percentiles",
               "spc_hail_04_hour_probability",
               "spc_tornado_04_hour_probability",
               "spc_wind_04_hour_probability",
               "temperature",
               "temperature_standard_deviation",
               "thunderstorm_01_hour_probability",
               "thunderstorm_03_hour_probability",
               "thunderstorm_06_hour_probability",
               "thunderstorm_12_hour_probability",
               "thunderstorm_coverage",
               "total_cloud_cover",
               "total_cloud_cover_standard_deviation",
               "transport_wind_direction",
               "transport_wind_speed",
               "ventilation_rate",
               "vertically_integrated_liquid",
               "visibility",
               "visibility_probability",
               "wind_direction",
               "wind_gust",
               "wind_gust_standard_deviation",
               "wind_speed",
               "wind_speed_standard_deviation"
            ],
            "datetimes":[
               "2025-09-22T01:00:00",
               "2025-09-22T02:00:00",
               "2025-09-22T03:00:00",
               "2025-09-22T04:00:00",
               "2025-09-22T05:00:00",
               "2025-09-22T06:00:00",
               "2025-09-22T07:00:00",
               "2025-09-22T08:00:00",
               "2025-09-22T09:00:00",
               "2025-09-22T10:00:00",
               "2025-09-22T11:00:00",
               "2025-09-22T12:00:00",
               "2025-09-22T13:00:00",
               "2025-09-22T14:00:00",
               "2025-09-22T15:00:00",
               "2025-09-22T16:00:00",
               "2025-09-22T17:00:00",
               "2025-09-22T18:00:00",
               "2025-09-22T19:00:00",
               "2025-09-22T20:00:00",
               "2025-09-22T21:00:00",
               "2025-09-22T22:00:00",
               "2025-09-22T23:00:00",
               "2025-09-23T00:00:00",
               "2025-09-23T01:00:00",
               "2025-09-23T02:00:00",
               "2025-09-23T03:00:00",
               "2025-09-23T04:00:00",
               "2025-09-23T05:00:00",
               "2025-09-23T06:00:00",
               "2025-09-23T07:00:00",
               "2025-09-23T08:00:00",
               "2025-09-23T09:00:00",
               "2025-09-23T10:00:00",
               "2025-09-23T11:00:00",
               "2025-09-23T12:00:00",
               "2025-09-23T13:00:00",
               "2025-09-23T14:00:00",
               "2025-09-23T15:00:00",
               "2025-09-23T16:00:00",
               "2025-09-23T17:00:00",
               "2025-09-23T18:00:00",
               "2025-09-23T19:00:00",
               "2025-09-23T20:00:00",
               "2025-09-23T21:00:00",
               "2025-09-23T22:00:00",
               "2025-09-23T23:00:00",
               "2025-09-24T00:00:00",
               "2025-09-24T03:00:00",
               "2025-09-24T06:00:00",
               "2025-09-24T09:00:00",
               "2025-09-24T12:00:00",
               "2025-09-24T15:00:00",
               "2025-09-24T18:00:00",
               "2025-09-24T21:00:00",
               "2025-09-25T00:00:00",
               "2025-09-25T03:00:00",
               "2025-09-25T06:00:00",
               "2025-09-25T09:00:00",
               "2025-09-25T12:00:00",
               "2025-09-25T15:00:00",
               "2025-09-25T18:00:00",
               "2025-09-25T21:00:00",
               "2025-09-26T00:00:00",
               "2025-09-26T03:00:00",
               "2025-09-26T06:00:00",
               "2025-09-26T09:00:00",
               "2025-09-26T12:00:00",
               "2025-09-26T15:00:00",
               "2025-09-26T18:00:00",
               "2025-09-26T21:00:00",
               "2025-09-27T00:00:00",
               "2025-09-27T03:00:00",
               "2025-09-27T06:00:00",
               "2025-09-27T09:00:00",
               "2025-09-27T12:00:00",
               "2025-09-27T15:00:00",
               "2025-09-27T18:00:00",
               "2025-09-27T21:00:00",
               "2025-09-28T00:00:00",
               "2025-09-28T03:00:00",
               "2025-09-28T06:00:00",
               "2025-09-28T09:00:00",
               "2025-09-28T12:00:00",
               "2025-09-28T15:00:00",
               "2025-09-28T18:00:00",
               "2025-09-28T21:00:00",
               "2025-09-29T00:00:00",
               "2025-09-29T03:00:00",
               "2025-09-29T06:00:00",
               "2025-09-29T09:00:00",
               "2025-09-29T12:00:00",
               "2025-09-29T15:00:00",
               "2025-09-29T18:00:00",
               "2025-09-29T21:00:00",
               "2025-09-30T00:00:00",
               "2025-09-30T06:00:00",
               "2025-09-30T12:00:00",
               "2025-09-30T18:00:00",
               "2025-10-01T00:00:00",
               "2025-10-01T06:00:00",
               "2025-10-01T12:00:00",
               "2025-10-01T18:00:00",
               "2025-10-02T00:00:00",
               "2025-10-02T06:00:00",
               "2025-10-02T12:00:00",
               "2025-10-02T18:00:00",
               "2025-10-03T00:00:00"
            ],
            "desi":{
               "projDict":{
                  "proj":"+proj=lcc +lat_0=25 +lon_0=265 +lat_1=25 +lat_2=25 +x_0=0 +y_0=0 +R=6371200 +units=m +no_defs +type=crs",
                  "crs_wkt":"PROJCRS[\"unknown\",BASEGEOGCRS[\"unknown\",DATUM[\"unknown\",ELLIPSOID[\"unknown\",6371200,0,LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]]],PRIMEM[\"Greenwich\",0,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8901]]],CONVERSION[\"unknown\",METHOD[\"Lambert Conic Conformal (2SP)\",ID[\"EPSG\",9802]],PARAMETER[\"Latitude of false origin\",25,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8821]],PARAMETER[\"Longitude of false origin\",265,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8822]],PARAMETER[\"Latitude of 1st standard parallel\",25,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8823]],PARAMETER[\"Latitude of 2nd standard parallel\",25,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8824]],PARAMETER[\"Easting at false origin\",0,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8826]],PARAMETER[\"Northing at false origin\",0,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8827]]],CS[Cartesian,2],AXIS[\"(E)\",east,ORDER[1],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]],AXIS[\"(N)\",north,ORDER[2],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]]]",
                  "first_lat":-263793.73346456443,
                  "first_lon":-3271151.605837171,
                  "nx":2345,
                  "ny":2345,
                  "dx":2539.703,
                  "dy":2539.703
               }
            },
            "parameter-names-dict":{
               "apparent_temperature":{
                  "attrs":{
                     "grib_section3":[
                        0,
                        3744965,
                        0,
                        0,
                        30,
                        1,
                        0,
                        6371200,
                        255,
                        255,
                        255,
                        255,
                        2345,
                        1597,
                        19229000,
                        233723400,
                        48,
                        25000000,
                        265000000,
                        2539703,
                        2539703,
                        0,
                        80,
                        25000000,
                        25000000,
                        -90000000,
                        0
                     ],
                     "long_name":"Apparent Temperature",
                     "short_name":"APTMP",
                     "units":"K",
                     "originating_center":"US National Weather Service - NCEP (WMC)",
                     "originating_sub_center":"NWS Meteorological Development Laboratory",
                     "master_table_info":"Version Implemented on 7 November 2001",
                     "product_definition_template_number":"Analysis or forecast at a horizontal level or in a horizontal layer at a point in time. (see Template 4.0)",
                     "type_of_generating_process":"Forecast",
                     "type_of_first_fixed_surface":"Specified Height Level Above Ground (m)",
                     "type_of_second_fixed_surface":"Missing (unknown)",
                     "crs_wkt":"PROJCRS[\"unknown\",BASEGEOGCRS[\"unknown\",DATUM[\"unknown\",ELLIPSOID[\"unknown\",6371200,0,LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]]],PRIMEM[\"Greenwich\",0,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8901]]],CONVERSION[\"unknown\",METHOD[\"Lambert Conic Conformal (2SP)\",ID[\"EPSG\",9802]],PARAMETER[\"Latitude of false origin\",25,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8821]],PARAMETER[\"Longitude of false origin\",265,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8822]],PARAMETER[\"Latitude of 1st standard parallel\",25,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8823]],PARAMETER[\"Latitude of 2nd standard parallel\",25,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8824]],PARAMETER[\"Easting at false origin\",0,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8826]],PARAMETER[\"Northing at false origin\",0,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8827]]],CS[Cartesian,2],AXIS[\"(E)\",east,ORDER[1],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]],AXIS[\"(N)\",north,ORDER[2],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]]]",
                     "gridlength_x_direction":2539.703,
                     "gridlength_y_direction":2539.703,
                     "latitude_first_gridpoint":19.229,
                     "longitude_first_gridpoint":233.7234,
                     "standard_name":"apparent_air_temperature",
                     "coordinates":"forecast_reference_time lead_time specified_height_level_above_ground",
                     "_FillValue":"AAAAAAAA+H8="
                  },
                  "time":[
                     "2025-09-22T01:00:00",
                     "2025-09-22T02:00:00",
                     "2025-09-22T03:00:00",
                     "2025-09-22T04:00:00",
                     "2025-09-22T05:00:00",
                     "2025-09-22T06:00:00",
                     "2025-09-22T07:00:00",
                     "2025-09-22T08:00:00",
                     "2025-09-22T09:00:00",
                     "2025-09-22T10:00:00",
                     "2025-09-22T11:00:00",
                     "2025-09-22T12:00:00",
                     "2025-09-22T13:00:00",
                     "2025-09-22T14:00:00",
                     "2025-09-22T15:00:00",
                     "2025-09-22T16:00:00",
                     "2025-09-22T17:00:00",
                     "2025-09-22T18:00:00",
                     "2025-09-22T19:00:00",
                     "2025-09-22T20:00:00",
                     "2025-09-22T21:00:00",
                     "2025-09-22T22:00:00",
                     "2025-09-22T23:00:00",
                     "2025-09-23T00:00:00",
                     "2025-09-23T01:00:00",
                     "2025-09-23T02:00:00",
                     "2025-09-23T03:00:00",
                     "2025-09-23T04:00:00",
                     "2025-09-23T05:00:00",
                     "2025-09-23T06:00:00",
                     "2025-09-23T07:00:00",
                     "2025-09-23T08:00:00",
                     "2025-09-23T09:00:00",
                     "2025-09-23T10:00:00",
                     "2025-09-23T11:00:00",
                     "2025-09-23T12:00:00",
                     "2025-09-23T13:00:00",
                     "2025-09-23T14:00:00",
                     "2025-09-23T15:00:00",
                     "2025-09-23T16:00:00",
                     "2025-09-23T17:00:00",
                     "2025-09-23T18:00:00",
                     "2025-09-23T19:00:00",
                     "2025-09-23T20:00:00",
                     "2025-09-23T21:00:00",
                     "2025-09-23T22:00:00",
                     "2025-09-23T23:00:00",
                     "2025-09-24T00:00:00",
                     "2025-09-24T03:00:00",
                     "2025-09-24T06:00:00",
                     "2025-09-24T09:00:00",
                     "2025-09-24T12:00:00",
                     "2025-09-24T15:00:00",
                     "2025-09-24T18:00:00",
                     "2025-09-24T21:00:00",
                     "2025-09-25T00:00:00",
                     "2025-09-25T03:00:00",
                     "2025-09-25T06:00:00",
                     "2025-09-25T09:00:00",
                     "2025-09-25T12:00:00",
                     "2025-09-25T15:00:00",
                     "2025-09-25T18:00:00",
                     "2025-09-25T21:00:00",
                     "2025-09-26T00:00:00",
                     "2025-09-26T03:00:00",
                     "2025-09-26T06:00:00",
                     "2025-09-26T09:00:00",
                     "2025-09-26T12:00:00",
                     "2025-09-26T15:00:00",
                     "2025-09-26T18:00:00",
                     "2025-09-26T21:00:00",
                     "2025-09-27T00:00:00",
                     "2025-09-27T03:00:00",
                     "2025-09-27T06:00:00",
                     "2025-09-27T09:00:00",
                     "2025-09-27T12:00:00",
                     "2025-09-27T15:00:00",
                     "2025-09-27T18:00:00",
                     "2025-09-27T21:00:00",
                     "2025-09-28T00:00:00",
                     "2025-09-28T03:00:00",
                     "2025-09-28T06:00:00",
                     "2025-09-28T09:00:00",
                     "2025-09-28T12:00:00",
                     "2025-09-28T15:00:00",
                     "2025-09-28T18:00:00",
                     "2025-09-28T21:00:00",
                     "2025-09-29T00:00:00",
                     "2025-09-29T03:00:00",
                     "2025-09-29T06:00:00",
                     "2025-09-29T09:00:00",
                     "2025-09-29T12:00:00",
                     "2025-09-29T15:00:00",
                     "2025-09-29T18:00:00",
                     "2025-09-29T21:00:00",
                     "2025-09-30T00:00:00",
                     "2025-09-30T06:00:00",
                     "2025-09-30T12:00:00",
                     "2025-09-30T18:00:00",
                     "2025-10-01T00:00:00",
                     "2025-10-01T06:00:00",
                     "2025-10-01T12:00:00",
                     "2025-10-01T18:00:00",
                     "2025-10-02T00:00:00",
                     "2025-10-02T06:00:00",
                     "2025-10-02T12:00:00",
                     "2025-10-02T18:00:00",
                     "2025-10-03T00:00:00"
                  ]
               }
            }
         }
      }
   ]
}
....
====
