[[core-section]]

== Requirements Class Core

include::../requirements/requirements_class_nwsviz-application-profile.adoc[]

=== Profiling Requirements

Implementations of the Profile are conformant with OGC API-EDR Part 1

include::../requirements/core/REQ_EDR-conformant.adoc[]


=== Platform Resources

OGC API — Common defines a set of common capabilities which are applicable to any OGC Web API. Those capabilities provide the platform upon which resource-specific APIs can be built. This section describes those capabilities and any modifications needed to better support spatio-temporal data resources.

.Platform Resource Paths
[width="100%",options="header,footer"]
|====================
|PATH TEMPLATE |METHOD |RESOURCE
|{root}/ |GET |Landing page
|{root}/api |GET |API Description (optional)
|{root}/conformance |GET |Conformance Classes
|====================

Where: {root} = Base URI for the API server

==== API Landing Page 

Path = {root}/

Dependencies 

* <<OGC19-072,OGC API — Common — Part 1: Core>>
* <<ogc-edr,OGC API-Environmental Data Retrieval Standard - Part 1.2: Core>>
* <<ogc-edr,OGC API-Environmental Data Retrieval Standard - Part 3 Service Profiles>>

The landing page provides links that support exploration of the resources offered via the API. The most important component of a landing page is a list of links. The Landing Page resource is initially defined in the Core conformance class of the <<OGC19-072,OGC API — Common - Part 1>> Standard. The <<ogc-edr,OGC API-Environmental Data Retrieval Standard>> Standard does not make any changes to this definition.

The normative JSON Schema for an OGC API-EDR Landing Page is defined in the https://schemas.opengis.net/ogcapi/edr/1.1/openapi/schemas/core/landingPage.yaml[LandingPage.yaml] document. While this schema provides a rich body of information about the API, only the Links property is required. 

Profiles of the <<ogc-edr,OGC API-Environmental Data Retrieval Standard>> are expected to provide a richer description of the API. The additional content that Profiles should mandate is defined in the following requirements.

include::../requirements/core/REQ_root.adoc[]

==== API Definition 

Path = {root}/api

Dependencies 

* <<OGC19-072,OGC API — Common — Part 1: Core>>
* <<ogc-edr,OGC API-Environmental Data Retrieval Standard>>

Every API is required to provide a definition document that describes the capabilities of that API. This definition document can be used by developers to understand the API, by software clients to connect to the server, or by development tools to support the implementation of servers and clients. The API Definition resource is initially defined in the Core conformance class of the <<OGC19-072,OGC API — Common - Part 1>> Standard. The <<ogc-edr,OGC API-Environmental Data Retrieval Standard>> does not make any changes to this definition.

NOTE: At this time only OpenAPI 3.0 and OpenAPI 3.1 documents are supported by OGC Web API Standards.

Profiles of the <<ogc-edr,OGC API-Environmental Data Retrieval Standard>> are required to provide an OpenAPI 3.1 document. This document extends the API definition provided by the OGC API-EDR Standard. These extensions reflect the additional requirements added by the Profile. Implementors of the profile will then build on that document to produce the API definition document for their implementation.

==== Declaration of Conformance Classes

Path = {root}/conformance

Dependencies 

* <<OGC19-072,OGC API — Common — Part 1: Core>>
* <<ogc-edr,OGC API-Environmental Data Retrieval Standard>>
* <<ogc-edr,OGC API-Environmental Data Retrieval Standard - Part 3 Service Profiles>>

To support “generic” clients that want to access implementations of multiple OGC API Standards and extensions — and not “just” a specific API server, the API has to declare the conformance classes it claims to have implemented. The Conformance Classes resource is initially defined in the Core conformance class of the <<OGC19-072,OGC API — Common - Part 1>> Standard. The <<ogc-edr,OGC API-Environmental Data Retrieval Standard>> Standard does not make any changes to this definition.

Profiles of the <<ogc-edr,OGC API-Environmental Data Retrieval Standard>> have additional requirements governing which Conformance Classes and identifiers must be included in this resource.



NOTE: OpenAPI 3.0 and OpenAPI 3.1 are two distinct Conformance Classes in the OGC API-EDR Standard. This requirement can be addressed in a Profile by including the appropriate conformance classes at {root}/conformance. 

NOTE: Get guidence from the OGC Naming Authority on valid URIs for Profiles. 

=== Spatio-temporal and Information Resources

.Spatial-temporal and Information Resource Paths
[width="100%",options="header,footer"]
|====================
|PATH TEMPLATE |METHOD |RESOURCE
|{root}/collections|GET |Metadata describing the Collections of data available from this API.
|{root}/collections/{collectionId} |GET |Metadata describing the Collection of data which has the unique identifier{collectionId}
|====================

Where:

* {root} = Base URI for the API server
* {collectionId} = an identifier for a specific Collection of data

==== Collections

OGC API implementations typically organize their geospatial resources into Collections. Information about those is accessed through the /collections path and the http://www.opengis.net/def/rel/ogc/1.0/data link relation.

Path = {root}/collections

Dependencies 

* <<OGC20-024,OGC API — Common — Part 2: Geospatial Data>>
* <<ogc-edr,OGC API-Environmental Data Retrieval Standard>>

The Collections resource is initially defined in the `Collections` conformance class of the <<OGC20-024,OGC API — Common - Part 2>> Standard. The <<ogc-edr,OGC API-Environmental Data Retrieval Standard>> Standard does not make any changes to this definition.


==== Collection Description

Each resource Collection is described by a set of metadata. That metadata can be accessed directly using the /collections/{collectionId} path and as an entry in the Collections property of the /collections response.

Path:

* {root}/collections (returns metadata for every Collection)
* {root}/collections/{collectionId} (returns metadata for the specified Collection)

Dependencies 

* <<OGC20-024,OGC API — Common — Part 2: Geospatial Data>>
* <<ogc-edr,OGC API-Environmental Data Retrieval Standard>>

===== Collection ID restictions

include::../requirements/core/REQ_collectionid.adoc[]

===== Extent property restrictions

The Collection metadata includes an Extent property which defines a spatial-temporal envelope that encompasses the geospatial data in the Collection.

include::../requirements/core/REQ_extent.adoc[]

===== Parameter_names property restrictions

The Collection metadata includes an Parameter_names property which defines the data parameters that are available in the Collection

include::../requirements/core/REQ_NBM-parameter-names.adoc[]
include::../requirements/core/REQ_MRMS-parameter-names.adoc[]

=== Query Resources

.Query Resource Paths
[width="100%",options="header,footer"]
|====================
|PATH TEMPLATE |METHOD |RESOURCE
|{root}/collections/{collectionId}/{queryType} |GET, POST(Optional) |Retrieve data according to the query pattern from a Collection with the unique identifier {collectionId}
|{root}/collections/{collectionId}/instances |GET |Retrieve metadata about instances of a collection
|{root}/collections/{collectionId}/instances/{instanceId} |GET |Retrieve metadata from a specific instanceof a Collection with the unique identifiers{collectionId} and {instanceId}
|{root}/collections/{collectionId}/instances/{instanceId}/{queryType} |GET, POST(Optional) |Retrieve data according to the query pattern from a specific instance of a Collection with the unique identifiers{collectionId} and {instanceId}
|====================

Where:

* {root} = Base URI for the API server
* {collectionId} = an identifier for a specific Collection of data
* {instanceId} = an identifier for a specific version or instance of a Collection of data
* {queryType} = an identifier for a specific query pattern to retrieve data from a specific  Collection of data

Path = {root}/collections/{collectionId}/{queryType}

Dependencies: <<ogc-edr,OGC API-Environmental Data Retrieval Standard>>

include::../requirements/core/REQ_data-query.adoc[]


==== Parameters

The following parameters are supported by all OGC API-EDR queries.

===== Output Format parameter

Data format for the output data (available options are listed in the collectionsresponse).

include::../requirements/core/REQ_output-format.adoc[]

===== Parameter queryType

Path -  Instance Query {root}/collections/{collectionId}/instances/{instanceId}/{queryType}


==== Position Query

The Position query returns data for the requested coordinate. Logic for identifying the best match for the coordinate will depend on the Collection and is at the discretion of the query service implementer. 

Path = {root}/collections/{collectionId}/instances/{instanceId}/position 

Dependencies: <<ogc-edr,OGC API-Environmental Data Retrieval Standard>>

include::../requirements/core/REQ_data-query-position.adoc[]


==== Items Query

The Items query allows a user to query a resource based on a unique identifier.

Path = {root}/collections/{collectionId}/instances/{instanceId}/items

Dependencies: <<ogc-edr,OGC API-Environmental Data Retrieval Standard>>

include::../requirements/core/REQ_data-query-items.adoc[]

==== Locations Query

The Location query returns a GeoJSON Feature Collection containing the available locations with a collection

Path = {root}/collections/{collectionId}/instances/{instanceId}/locations

Dependencies: <<ogc-edr,OGC API-Environmental Data Retrieval Standard>>

include::../requirements/core/REQ_data-query-locations.adoc[]

==== Location Query

The Location query returns a location defined by a bounding box dependent on the indices of i and j.

Path = {root}/collections/{collectionId}/instances/{instanceId}/locations/{locationId}

Dependencies: <<ogc-edr,OGC API-Environmental Data Retrieval Standard>>

include::../requirements/core/REQ_data-query-location.adoc[]

==== Instances Query

Having multiple versions or instances of the same Collection, where the same information is reprocessed or regenerated is not unusual. Although these versions could be described as new Collections the instance query type allows this data to be described as different views of the same Collection.

Path = {root}/collections/{collectionId}/instances

Dependencies: <<ogc-edr,OGC API-Environmental Data Retrieval Standard>>

include::../requirements/core/REQ_data-query-instances.adoc[]


=== General Requirements

==== HTTP Status Codes

HTTP response

 - Response status codes
 
include::../requirements/core/REQ_status-codes.adoc[]

==== Links

 - Response links

include::../requirements/core/REQ_links.adoc[]





