[[ats_nwsviz-application_status-codes]]
[abstract_test]
====
[%metadata]
identifier:: /conf/nwsviz-application/status-codes
target:: /req/nwsviz-application/status-codes
test-purpose:: Verify that NWSViz profile Collection has the correct HTTP status responses.
test-method::
step:: Verify that a valid request returns a HTTP status code of 200
step:: Verify that a valid request with an empty response returns a HTTP status code of 204
step:: Verify that a request with an invalid query parameter value returns a HTTP status code of 400 
step:: Verify that that an unsupported HTTP method request returns a HTTP status code of 405.
step:: Verify that a request for too much data returns a HTTP status code of 413.
step:: Verify that a invalid request caused by an unexpected error returns a HTTP status code of 500.

====

[abstract_test]
====
[%metadata]
identifier:: /conf/nwsviz-application/msg-bodies
target:: /req/nwsviz-application/msg-bodies
test-purpose:: Verify that NWSViz profile error response messages have the correct structure.
test-method::
step:: Verify the the message body returned by error messages (status codes 400,405,413 and 500) is JSON based on the following schema: 

[source,JSON]
----
{
    "type": "object",
    "required": [
        "code"
    ],
    "properties": {
        "code": {
            "type": "string"
        },
        "description": {
            "type": "string"
        }
    }
}
----

====