[[ats_nwsviz-application_extent]]
[abstract_test]
====
[%metadata]
identifier:: /conf/nwsviz-application/extent
target:: /req/nwsviz-application/extent
test-purpose:: Verify that NWSViz profile Collection Extent is correctly defined in the Collection response. 
test-method:: 
step:: Verify that the collection contains a spatial extent and contain an additional attribute named "locations" containing the a list of the available locations within the collection.
[source,JSON]
----
{
   "spatial":{
      "bbox":[
         -180,
         -90,
         180,
         90
      ],
      "locations":[
         "CO",
         "AK",
         "HI"
      ]
   }
}
----

part:: Verify that the Profile contains a temporal extent containing an interval and values. 
part:: Verify that the Profile contains an attribute named instances which contains a list of available instances for the collection.
part:: Verify that the Profile contains a custom query dimension with the name "ensemble" containing values and ids.
part:: Verify that the Profile contains a vertical extent if applicable


====