[[ats_root]]
[abstract_test]
====
[%metadata]
identifier:: /conf/vertical-extent-demo/root
target:: /req/vertical-extent-demo_data/root
test-purpose:: Validate that the profile defines the service landing page
test-method:: 
step:: Verify that the profile defines a *Title* for the service and the value is *"Vertical extent demo service"*
step:: Verify that each link defined for the service has a *href* and *rel* attribute.
step:: Verify that the  *Keywords* attribute has the following values:

    * Geopotential Height
    * Pressure Level
    * Specific humidity
    * Air temperature
    * u-component of wind
    * v-component of wind

step:: Verify that the *Provider* attribute has *name* and *url* attributes defined.
step:: Verify that the *Contact* attribute has an *email* attributes defined.
step:: Verify that the *Links* property includes the following link to the OpenAPI definition of the profile:

[source,JSON]
----
    {
        "title": "OpenAPI definition of Vertical extent demo profile",
        "href": "https://www.example.org/edr/profile/vextdemo/openapi.json",
        "rel": "profile",
        "type": "application/json"
    }
----
====