[[ats_nwsviz-application_data-query-locations]]
[abstract_test]
====
[%metadata]
identifier:: /conf/nwsviz-application/data-query-locations
target:: /req/nwsviz-application/data-query-locations
test-purpose:: Verify that NWSViz profile Collection *Locations* query is correctly defined in the Collection response.
test-method:: 
step:: Verify that NWSViz profile Collection *Locations* query defines the following output_format types

        * GeoJSON

step:: Verify that NWSViz profile Collection *Locations* query defines the following default output_format.

    * CoverageJSON

step:: Verify that NWSViz profile Collection *Locations* requirement supports the following HTTP operations

    * GET
    * POST

step:: Verify that the reponse provides a listing of the available locations in a collection that conforms to GeoJSON and contains the properties contained in this example:

[source,JSON]
....
{
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "geometry":{
            "type":"Polygon",
            "coordinates":[
               [
                  [
                     2681912.2261628294,
                     -263793.73346456443
                  ],
                  [
                     2681912.2261628294,
                     3789572.2545354357
                  ],
                  [
                     -3271151.605837171,
                     3789572.2545354357
                  ],
                  [
                     -3271151.605837171,
                     -263793.73346456443
                  ],
                  [
                     2681912.2261628294,
                     -263793.73346456443
                  ]
               ]
            ]
         },
         "properties":{
            "instance":"2025-09-22T00:00:00",
            "name":"conus",
            "name_alt":"http://edr-api-desi-c.mdl.nws.noaa.gov/collections/NBM_icechunk/instances/2025-09-22T00:00:00/locations/conus?f=json",
            "edrqueryendpoint":"http://edr-api-desi-c.mdl.nws.noaa.gov/collections/NBM_icechunk/instances/2025-09-22T00:00:00/locations/conus?f=json",
            "parameter-names":[
               "apparent_temperature",
               "ceiling",
               "ceiling_probability",
               "cloud_base",
               "conditional_probability_of_precipitation_type",
               "convective_available_potential_energy",
               "convective_available_potential_energy_percentiles",
               "convective_available_potential_energy_standard_deviation",
               "dewpoint",
               "dewpoint_standard_deviation",
               "downward_shortwave_radiation_flux",
               "dry_thunderstorm_probability",
               "echo_top",
               "ellrod_index",
               "fosberg_index_06_hour",
               "ice_accumulation_01_hour",
               "ice_accumulation_06_hour",
               "ice_accumulation_06_hour_percentiles",
               "low_level_turbulence",
               "low_level_wind_shear_altitude",
               "low_level_wind_shear_direction",
               "low_level_wind_shear_magnitude",
               "maximum_reflectivity",
               "maximum_relative_humidity_12_hour",
               "maximum_temperature_12_hour",
               "maximum_temperature_12_hour_standard_deviation",
               "minimum_relative_humidity_12_hour",
               "minimum_temperature_12_hour",
               "minimum_temperature_12_hour_standard_deviation",
               "mixing_height",
               "precipitable_water",
               "precipitable_water_percentiles",
               "precipitation_01_hour_probability",
               "precipitation_06_hour_probability",
               "precipitation_12_hour_probability",
               "precipitation_accumulation_01_hour",
               "precipitation_accumulation_06_hour",
               "precipitation_duration_12_hour",
               "predominant_weather",
               "relative_humidity",
               "sea_surface_temperature",
               "snow_accumulation_01_hour",
               "snow_accumulation_01_hour_percentiles",
               "snow_accumulation_06_hour",
               "snow_accumulation_06_hour_percentiles",
               "snow_level",
               "snow_level_percentiles",
               "snow_liquid_ratio",
               "snow_liquid_ratio_percentiles",
               "spc_hail_04_hour_probability",
               "spc_tornado_04_hour_probability",
               "spc_wind_04_hour_probability",
               "temperature",
               "temperature_standard_deviation",
               "thunderstorm_01_hour_probability",
               "thunderstorm_03_hour_probability",
               "thunderstorm_06_hour_probability",
               "thunderstorm_12_hour_probability",
               "thunderstorm_coverage",
               "total_cloud_cover",
               "total_cloud_cover_standard_deviation",
               "transport_wind_direction",
               "transport_wind_speed",
               "ventilation_rate",
               "vertically_integrated_liquid",
               "visibility",
               "visibility_probability",
               "wind_direction",
               "wind_gust",
               "wind_gust_standard_deviation",
               "wind_speed",
               "wind_speed_standard_deviation"
            ],
            "datetimes":[
               "2025-09-22T01:00:00",
               "2025-09-22T02:00:00",
               "...etc",
            ],
            "desi":{
               "projDict":{
                  "proj":"+proj=lcc +lat_0=25 +lon_0=265 +lat_1=25 +lat_2=25 +x_0=0 +y_0=0 +R=6371200 +units=m +no_defs +type=crs",
                  "crs_wkt":"PROJCRS[\"unknown\",BASEGEOGCRS[\"unknown\",DATUM[\"unknown\",ELLIPSOID[\"unknown\",6371200,0,LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]]],PRIMEM[\"Greenwich\",0,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8901]]],CONVERSION[\"unknown\",METHOD[\"Lambert Conic Conformal (2SP)\",ID[\"EPSG\",9802]],PARAMETER[\"Latitude of false origin\",25,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8821]],PARAMETER[\"Longitude of false origin\",265,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8822]],PARAMETER[\"Latitude of 1st standard parallel\",25,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8823]],PARAMETER[\"Latitude of 2nd standard parallel\",25,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8824]],PARAMETER[\"Easting at false origin\",0,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8826]],PARAMETER[\"Northing at false origin\",0,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8827]]],CS[Cartesian,2],AXIS[\"(E)\",east,ORDER[1],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]],AXIS[\"(N)\",north,ORDER[2],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]]]",
                  "first_lat":-263793.73346456443,
                  "first_lon":-3271151.605837171,
                  "nx":2345,
                  "ny":2345,
                  "dx":2539.703,
                  "dy":2539.703
               }
            },
            "parameter-names-dict":{
               "apparent_temperature":{
                  "attrs":{
                     "grib_section3":[
                        0,
                        3744965,
                        0,
                        0,
                        30,
                        1,
                        0,
                        6371200,
                        255,
                        255,
                        255,
                        255,
                        2345,
                        1597,
                        19229000,
                        233723400,
                        48,
                        25000000,
                        265000000,
                        2539703,
                        2539703,
                        0,
                        80,
                        25000000,
                        25000000,
                        -90000000,
                        0
                     ],
                     "long_name":"Apparent Temperature",
                     "short_name":"APTMP",
                     "units":"K",
                     "originating_center":"US National Weather Service - NCEP (WMC)",
                     "originating_sub_center":"NWS Meteorological Development Laboratory",
                     "master_table_info":"Version Implemented on 7 November 2001",
                     "product_definition_template_number":"Analysis or forecast at a horizontal level or in a horizontal layer at a point in time. (see Template 4.0)",
                     "type_of_generating_process":"Forecast",
                     "type_of_first_fixed_surface":"Specified Height Level Above Ground (m)",
                     "type_of_second_fixed_surface":"Missing (unknown)",
                     "crs_wkt":"PROJCRS[\"unknown\",BASEGEOGCRS[\"unknown\",DATUM[\"unknown\",ELLIPSOID[\"unknown\",6371200,0,LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]]],PRIMEM[\"Greenwich\",0,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8901]]],CONVERSION[\"unknown\",METHOD[\"Lambert Conic Conformal (2SP)\",ID[\"EPSG\",9802]],PARAMETER[\"Latitude of false origin\",25,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8821]],PARAMETER[\"Longitude of false origin\",265,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8822]],PARAMETER[\"Latitude of 1st standard parallel\",25,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8823]],PARAMETER[\"Latitude of 2nd standard parallel\",25,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8824]],PARAMETER[\"Easting at false origin\",0,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8826]],PARAMETER[\"Northing at false origin\",0,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8827]]],CS[Cartesian,2],AXIS[\"(E)\",east,ORDER[1],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]],AXIS[\"(N)\",north,ORDER[2],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]]]",
                     "gridlength_x_direction":2539.703,
                     "gridlength_y_direction":2539.703,
                     "latitude_first_gridpoint":19.229,
                     "longitude_first_gridpoint":233.7234,
                     "standard_name":"apparent_air_temperature",
                     "coordinates":"forecast_reference_time lead_time specified_height_level_above_ground",
                     "_FillValue":"AAAAAAAA+H8="
                  },
                  "time":[
                     "2025-09-22T01:00:00",
                     "2025-09-22T02:00:00",
                     "...etc"
                  ]
               }
            },
            "bbox":[
               -3271151.605837171,
               -263793.73346456443,
               2681912.2261628294,
               3789572.2545354357
            ]
         }
      }
   ]
}
....
====