[[req_class_nwsviz-application]]
[requirements_class]
.Requirements Class 'NWSViz Application'
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-edr-3/1.0/req/nwsviz-application
target-type:: NWSViz Application Profile Standard
requirement:: /req/nwsviz-application/root
requirement:: /req/nwsviz-application/edr-conformant
requirement:: /req/nwsviz-application/parameter-names
requirement:: /req/nwsviz-application/NBM-parameter-names
requirement:: /req/nwsviz-application/MRMS-parameter-names
requirement:: /req/nwsviz-application/collectionid
requirement:: /req/nwsviz-application/extent
requirement:: /req/nwsviz-application/data-query
requirement:: /req/nwsviz-application/output-format
requirement:: /req/nwsviz-application/data-query-position
requirement:: /req/nwsviz-application/data-query-instances
requirement:: /req/nwsviz-application/data-query-location
requirement:: /req/nwsviz-application/data-query-locations
requirement:: /req/nwsviz-application/data-query-items
requirement:: /req/nwsviz-application/status-codes
requirement:: /req/nwsviz-application/msg-bodies
requirement:: /req/nwsviz-application/links
requirement:: /req/nwsviz-application/differencing-processes

====


