[[ats_class-nwsviz-application]]
[conformance_class]
.Conformance Class 'Core'
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-edr-3/1.0/conf/nwsviz-application
target:: http://www.opengis.net/spec/ogcapi-edr-3/1.0/req/nwsviz-application
abstract-test:: /conf/nwsviz-application/root
abstract-test:: /conf/nwsviz-application/edr-conformant
abstract-test:: /conf/nwsviz-application/MRMS-parameter-names
abstract-test:: /conf/nwsviz-application/NBM-parameter-names
abstract-test:: /conf/nwsviz-application/collectionid
abstract-test:: /conf/nwsviz-application/extent
abstract-test:: /conf/nwsviz-application/output-format
abstract-test:: /conf/nwsviz-application/status-codes
abstract-test:: /conf/nwsviz-application/msg-bodies
abstract-test:: /conf/nwsviz-application/links
abstract-test:: /conf/nwsviz-application/data-query
abstract-test:: /conf/nwsviz-application/data-query-instances
abstract-test:: /conf/nwsviz-application/data-query-position
abstract-test:: /conf/nwsviz-application/data-query-items
abstract-test:: /conf/nwsviz-application/data-query-location
abstract-test:: /conf/nwsviz-application/data-query-locations
abstract-test:: /conf/nwsviz-application/differencing-processes
====

